[package]
name = "sym-proof"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
witness-checker = { path = "../witness-checker", package = "cheesecloth" }

serde = { version = "1", features = ["derive"] }
serde_cbor = "0.10"
serde_json = "1"
serde_yaml = "0.8"

log = "0.4"
env_logger = "0.7"
bumpalo = "3.14.0"

[features]
verbose = []
debug_symbolic = []

recording_1 = []
playback_1 = []
