import cbor
from pprint import pprint
import sys
import time

cbor_path, = sys.argv[1:]

c = cbor.load(open(cbor_path, 'rb'))


print('// AUTOMATICALLY GENERATED by %s at %s' % (sys.argv[0], time.asctime(time.localtime())))
print()

print('pub const CPU_STATE_PC: u64 = %d;' % c['pc'])
print('pub const CPU_STATE_CYCLE: u64 = %d;' % c['cycle'])

regs = c['regs']
print('pub const CPU_STATE_REGS: [u64; %d] = [' % len(regs))
for i in range(0, len(regs), 8):
    print('    ' + ' '.join('%d,' % x for x in regs[i : i + 8]))
print('];');

print()
mem = c['mem']
print('pub static MEM_ADVICE: [(u64, u64); %d] = [' % len(mem))
for addr, value in mem:
    print('    (0x%x, %d),' % (addr, value))
print('];')
